"""The Mol-R1 reasoning self-improvement loop (MoIA in arXiv v1).

    R^0 = seed traces (PRID)
    for T = 0, 1, ...:
        Imitate  SFT of the base model on R^T                   θ_0  -> θ̂^T
        Explore  GRPO on the training set, exact-match reward   θ̂^T -> θ^{T+1}
        Harvest  θ^{T+1} samples traces for every training instance and keeps
                 the first verified one; merged with R^T it forms R^{T+1}
                 (instances the new policy re-solves get the new trace)
    stop when R^{T+1} covers the training set, grows by less than --min_growth,
    or after --max_iterations.

After the seed, every training trace is generated by the policy itself.

Each stage writes to work_dir/iter_T/ and is skipped if its output exists, so an
interrupted run resumes where it stopped. Per-iteration coverage, churn and
harvest cost are appended to work_dir/loop_log.json; churn is measured on the
harvest before merging, so "lost" counts instances the new policy failed to
re-solve.
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from src.common import dump_json, load_json, load_tsv, parse_entry
from src.rsi.harvest import merge_shards, shard_paths
from src.rsi.stats import compare, resolve_ids, summarize

SFT = ROOT / "src" / "train" / "sft_train.py"
RL = ROOT / "src" / "train" / "grpo_train.py"
HARVEST = ROOT / "src" / "rsi" / "harvest.py"
PREDICT = ROOT / "src" / "eval" / "predict.py"
EVALUATE = ROOT / "src" / "eval" / "evaluate.py"


def run(cmd, desc):
    cmd = [str(c) for c in cmd]
    print(f"\n{'=' * 60}\n[STEP] {desc}\n[CMD]  {' '.join(cmd)}\n{'=' * 60}", flush=True)
    subprocess.run(cmd, check=True)


def torchrun(n):
    return ["torchrun", f"--nproc_per_node={n}"]


def trained(model_dir):
    return (Path(model_dir) / "model.safetensors").exists()


def run_harvest(args, model_dir, out_dir):
    """Launch one harvest shard per GPU group in parallel; return the shard count."""
    os.makedirs(out_dir, exist_ok=True)
    visible = os.environ.get("CUDA_VISIBLE_DEVICES")
    devices = visible.split(",") if visible else [str(i) for i in range(args.harvest_gpus)]
    g = args.harvest_gpus_per_shard
    num_shards = args.harvest_gpus // g
    procs = []
    for i in range(num_shards):
        if Path(shard_paths(out_dir, i)[1]).exists():
            continue
        cmd = [sys.executable, HARVEST, "--model_dir", model_dir, "--train_data", args.train_data,
               "--output_dir", out_dir, "--shard_id", i, "--num_shards", num_shards,
               "--max_attempts", args.harvest_max_attempts,
               "--samples_per_round", args.harvest_samples_per_round,
               "--temperature", args.harvest_temperature, "--top_p", args.harvest_top_p,
               "--max_tokens", args.harvest_max_tokens, "--seed", args.seed,
               "--tensor_parallel_size", g]
        if args.no_require_format:
            cmd.append("--no_require_format")
        env = dict(os.environ, CUDA_VISIBLE_DEVICES=",".join(devices[i * g:(i + 1) * g]))
        log = open(Path(out_dir) / f"shard_{i}.log", "w")
        print(f"[harvest] shard {i}/{num_shards} on GPUs {env['CUDA_VISIBLE_DEVICES']} (log: {log.name})",
              flush=True)
        procs.append((i, subprocess.Popen([str(c) for c in cmd], env=env, stdout=log,
                                          stderr=subprocess.STDOUT), log))
    failed = []
    for i, proc, log in procs:
        if proc.wait() != 0:
            failed.append(i)
        log.close()
    if failed:
        raise RuntimeError(f"Harvest shards {failed} failed; see {out_dir}/shard_*.log")
    return num_shards


def run_eval(args, model_dir, prefix):
    metrics = Path(f"{prefix}_metrics.json")
    if not metrics.exists():
        pred = f"{prefix}_predictions.txt"
        run(torchrun(args.eval_gpus) + [
            PREDICT, "--mode", "cot", "--model_dir", model_dir, "--test_path", args.eval_data,
            "--output_path", pred, "--temperature", args.eval_temperature,
            "--top_p", args.eval_top_p, "--max_tokens", args.eval_max_tokens,
        ], f"Evaluate {model_dir}")
        run([sys.executable, EVALUATE, pred, "--json_out", metrics], "Metrics")
    return load_json(metrics)


def merge_previous(prev_entries, prev_ids, harvested):
    """R^{T+1} = new harvest + R^T traces of instances the new policy did not re-solve."""
    have = {e["id"] for e in harvested}
    carried = []
    for d, i in zip(prev_entries, prev_ids):
        if i is None or i in have:
            continue
        if "conversations" in d:
            question, gt, content = parse_entry(d)
            d = {"question": question, "gt": gt, "content": content, "pred": gt, "score": 1}
        carried.append(dict(d, id=i, from_previous=True))
        have.add(i)
    return harvested + carried


def parse_args():
    p = argparse.ArgumentParser(description="Mol-R1 reasoning self-improvement loop")
    p.add_argument("--base_model", default="meta-llama/Llama-3.1-8B-Instruct")
    p.add_argument("--seed_data", default="data/MoIA/T0_zh.json", help="R^0 trace set")
    p.add_argument("--train_data", default="data/raw/chebi-20/train.txt")
    p.add_argument("--work_dir", default="outputs/rsi")
    p.add_argument("--seed", type=int, default=0)

    g = p.add_argument_group("loop")
    g.add_argument("--max_iterations", type=int, default=3)
    g.add_argument("--min_growth", type=float, default=0.01,
                   help="Stop when (|R^{T+1}| - |R^T|) / |R^T| falls below this")
    g.add_argument("--sft_init", choices=["base", "prev"], default="base",
                   help="base: every SFT stage restarts from the base model, as in STaR/ReST-EM "
                        "(the reported run); prev: continue from the previous RL policy")
    g.add_argument("--rl_data", choices=["train", "trace_set"], default="train",
                   help="train: RL on the full training set; trace_set: RL on R^T only")
    g.add_argument("--rebuild", action="store_true",
                   help="Build R^{T+1} from the new harvest only instead of merging it with R^T")
    g.add_argument("--no_final_harvest", action="store_true",
                   help="Skip the harvest after the last iteration")

    g = p.add_argument_group("imitate (SFT)")
    g.add_argument("--sft_gpus", type=int, default=2)
    g.add_argument("--sft_epochs", type=int, default=5)
    g.add_argument("--sft_lr", type=float, default=1e-5)
    g.add_argument("--sft_batch_size", type=int, default=1)
    g.add_argument("--sft_grad_accum", type=int, default=4)
    g.add_argument("--sft_max_seq_len", type=int, default=2048)

    g = p.add_argument_group("explore (GRPO)")
    g.add_argument("--rl_gpus", type=int, default=8)
    g.add_argument("--rl_epochs", type=int, default=2)
    g.add_argument("--rl_lr", type=float, default=1e-6)
    g.add_argument("--rl_num_generations", type=int, default=5)
    g.add_argument("--rl_temperature", type=float, default=1.0)
    g.add_argument("--rl_kl_coef", type=float, default=0.01)
    g.add_argument("--rl_global_batch_size", type=int, default=128)
    g.add_argument("--rl_rollout_batch_size", type=int, default=512)
    g.add_argument("--rl_micro_batch_size", type=int, default=4)
    g.add_argument("--rl_em_weight", type=float, default=1.0)
    g.add_argument("--rl_validity_weight", type=float, default=0.0)

    g = p.add_argument_group("harvest")
    g.add_argument("--harvest_gpus", type=int, default=8)
    g.add_argument("--harvest_gpus_per_shard", type=int, default=1)
    g.add_argument("--harvest_max_attempts", type=int, default=8)
    g.add_argument("--harvest_samples_per_round", type=int, default=8)
    g.add_argument("--harvest_temperature", type=float, default=1.0)
    g.add_argument("--harvest_top_p", type=float, default=1.0)
    g.add_argument("--harvest_max_tokens", type=int, default=4096)
    g.add_argument("--no_require_format", action="store_true")

    g = p.add_argument_group("evaluation (optional, reporting only)")
    g.add_argument("--eval_data", default=None,
                   help="Split to evaluate after each stage, e.g. data/raw/chebi-20/validation.txt")
    g.add_argument("--eval_stages", choices=["sft", "rl", "both"], default="both")
    g.add_argument("--eval_gpus", type=int, default=8)
    g.add_argument("--eval_temperature", type=float, default=0.6)
    g.add_argument("--eval_top_p", type=float, default=0.9)
    g.add_argument("--eval_max_tokens", type=int, default=10000)
    return p.parse_args()


def main():
    args = parse_args()
    work = Path(args.work_dir)
    work.mkdir(parents=True, exist_ok=True)
    train = load_tsv(args.train_data)
    log_path = work / "loop_log.json"
    log = {r["iteration"]: r for r in (load_json(log_path) if log_path.exists() else [])}

    for t in range(args.max_iterations):
        it = work / f"iter_{t}"
        it.mkdir(exist_ok=True)
        trace_set = it / "R.json"
        if t == 0 and not trace_set.exists():
            shutil.copy(args.seed_data, trace_set)
        entries = load_json(trace_set)
        ids_list = resolve_ids(entries, train)
        summary, ids = summarize(entries, ids_list, len(train))
        print(f"\n{'#' * 60}\n# ITERATION T={t}: |R^{t}| = {summary['unique_ids']} "
              f"({summary['coverage']:.1%} of the training set)\n{'#' * 60}", flush=True)

        # Imitate
        init = args.base_model if t == 0 or args.sft_init == "base" else work / f"iter_{t - 1}" / "rl" / "final"
        sft_dir = it / "sft"
        if not trained(sft_dir / "final"):
            run(torchrun(args.sft_gpus) + [
                SFT, "--mode", "cot", "--model_name", init, "--data_path", trace_set,
                "--output_dir", sft_dir, "--epochs", args.sft_epochs, "--lr", args.sft_lr,
                "--batch_size", args.sft_batch_size, "--grad_accum", args.sft_grad_accum,
                "--max_seq_len", args.sft_max_seq_len,
            ], f"[T={t}] Imitate: SFT on R^{t} from {init}")

        # Explore
        rl_dir = it / "rl"
        if not trained(rl_dir / "final"):
            run(torchrun(args.rl_gpus) + [
                RL, "--sft_model_dir", sft_dir / "final",
                "--data_path", args.train_data if args.rl_data == "train" else trace_set,
                "--output_dir", rl_dir, "--epochs", args.rl_epochs, "--lr", args.rl_lr,
                "--num_generations", args.rl_num_generations, "--temperature", args.rl_temperature,
                "--beta", args.rl_kl_coef, "--global_batch_size", args.rl_global_batch_size,
                "--rollout_batch_size", args.rl_rollout_batch_size,
                "--micro_batch_size", args.rl_micro_batch_size,
                "--em_weight", args.rl_em_weight, "--validity_weight", args.rl_validity_weight,
            ], f"[T={t}] Explore: GRPO on the {args.rl_data} set")

        record = {"iteration": t, "trace_set": summary, "sft_init": str(init)}
        if args.eval_data:
            if args.eval_stages in ("sft", "both"):
                record["eval_sft"] = run_eval(args, sft_dir / "final", it / "eval_sft")
            if args.eval_stages in ("rl", "both"):
                record["eval_rl"] = run_eval(args, rl_dir / "final", it / "eval_rl")

        stop = None
        if t == args.max_iterations - 1 and args.no_final_harvest:
            stop = "max_iterations"
        else:
            # Harvest, then merge with R^T
            nxt = work / f"iter_{t + 1}"
            nxt.mkdir(exist_ok=True)
            harvest_set, next_set = nxt / "harvest.json", nxt / "R.json"
            if not (nxt / "harvest_meta.json").exists():
                num_shards = run_harvest(args, rl_dir / "final", nxt / "harvest")
                dump_json(merge_shards(nxt / "harvest", num_shards, train, harvest_set),
                          nxt / "harvest_meta.json")
            meta = load_json(nxt / "harvest_meta.json")
            harvested = load_json(harvest_set)
            if not next_set.exists():
                dump_json(harvested if args.rebuild else merge_previous(entries, ids_list, harvested),
                          next_set)
            next_entries = load_json(next_set)

            harvest_summary, harvest_ids = summarize(harvested, [e["id"] for e in harvested], len(train))
            next_summary, _ = summarize(next_entries, resolve_ids(next_entries, train), len(train))
            churn = compare(ids, harvest_ids)
            growth = (next_summary["unique_ids"] - summary["unique_ids"]) / summary["unique_ids"]
            record.update(harvest=meta, harvest_set=harvest_summary, harvest_churn=churn,
                          carried_over=len(next_entries) - len(harvested),
                          next_trace_set=next_summary, growth=growth,
                          samples_per_new_trace=meta["samples_generated"] / churn["new"] if churn["new"] else None)
            print(f"[T={t}] Harvest: {harvest_summary['unique_ids']} solved "
                  f"(+{churn['new']} new, {churn['lost']} of R^{t} not re-solved, "
                  f"{meta['samples_generated']} samples); |R^{t + 1}| = {next_summary['unique_ids']}",
                  flush=True)
            if next_summary["unique_ids"] >= len(train):
                stop = "training set fully covered"
            elif growth < args.min_growth:
                stop = f"growth {growth:.4f} below {args.min_growth}"
            elif t == args.max_iterations - 1:
                stop = "max_iterations"

        record["stop"] = stop
        log[t] = record
        dump_json([log[k] for k in sorted(log)], log_path)
        if stop:
            print(f"\n[STOP] {stop}. Log: {log_path}")
            break


if __name__ == "__main__":
    main()
